// lib/scaffold.mjs — creates projects/<slug>/ for either stack
import fs from "node:fs";
import path from "node:path";
import { PROJECTS_DIR, ROOT } from "../config.mjs";
import { run } from "./run.mjs";

function writeSpec(dir, idea) {
  const spec = `# ${idea.title}
Category: ${idea.category} | Stack: ${idea.stack} | Aesthetic: ${idea.aesthetic}

> ${idea.description}

## Features
${idea.features.map(f=> `- ${f}`).join("\n")}

## Tags
${idea.tags.join(", ")}

## Notes
Auto-generated by auto-forge on ${new Date().toISOString()}. Edit SPEC.md before re-running the builder to iterate.
`;
  fs.writeFileSync(path.join(dir, "SPEC.md"), spec);
}

export async function scaffoldVite(idea) {
  const dest = path.join(PROJECTS_DIR, idea.slug);
  if (fs.existsSync(dest)) throw new Error(`exists: ${dest}`);
  fs.mkdirSync(dest, { recursive: true });

  // npm create vite (non-interactive)
  console.log(`  scaffolding vite → ${idea.slug}`);
  const r = await run("npm", ["create", "vite@latest", dest, "--", "--template", "react-ts"], { cwd: ROOT });
  if (r.code !== 0) throw new Error(`vite create failed: ${r.err.slice(0,800)}`);

  // tailwind v4: install + config
  await run("npm", ["install", "-D", "tailwindcss", "@tailwindcss/vite"], { cwd: dest });
  await run("npm", ["install"], { cwd: dest }); // ensure deps

  // patch vite.config.ts to add tailwind plugin
  const viteCfg = path.join(dest, "vite.config.ts");
  try {
    let cfg = fs.readFileSync(viteCfg, "utf8");
    if (!cfg.includes("@tailwindcss/vite")) {
      cfg = cfg.replace(`import { defineConfig } from 'vite'`, `import { defineConfig } from 'vite'\nimport tailwindcss from '@tailwindcss/vite'`);
      cfg = cfg.replace(/plugins:\s*\[/, `plugins: [tailwindcss(),`);
      fs.writeFileSync(viteCfg, cfg);
    }
  } catch {}

  // minimal index.css with tailwind import
  const cssPath = path.join(dest, "src", "index.css");
  fs.mkdirSync(path.join(dest, "src"), { recursive: true });
  if (!fs.existsSync(cssPath) || fs.readFileSync(cssPath,"utf8").length < 20) {
    fs.writeFileSync(cssPath, `@import "tailwindcss";\n`);
  }

  writeSpec(dest, idea);
  // per-project opencode.json will be written by daily.mjs
  return dest;
}

export async function scaffoldHtml(idea) {
  const dest = path.join(PROJECTS_DIR, idea.slug);
  if (fs.existsSync(dest)) throw new Error(`exists: ${dest}`);
  fs.mkdirSync(dest, { recursive: true });

  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${idea.title}</title>
  <link rel="stylesheet" href="./style.css" />
</head>
<body>
  <main id="app">
    <h1>${idea.title}</h1>
    <p class="sub">${idea.description}</p>
    <div id="stage"></div>
  </main>
  <script type="module" src="./app.js"></script>
</body>
</html>
`;
  const css = `*{box-sizing:border-box}body{margin:0;font:16px/1.5 system-ui,sans-serif;background:#0b0b0f;color:#e8e8ef}
#app{max-width:900px;margin:40px auto;padding:24px}
h1{font-size:32px;margin:0 0 8px}.sub{opacity:.7;margin:0 0 20px}
#stage{min-height:300px;border:1px dashed #333;border-radius:12px;display:grid;place-items:center;padding:20px}
`;
  const js = `// ${idea.title} — auto-forge html scaffold
// Spec: ${idea.features.join(" | ")}
const stage = document.getElementById("stage");
stage.textContent = "Built by auto-forge — replace with your idea.";
console.log("auto-forge html scaffold ready", ${JSON.stringify(idea.slug)});
`;
  fs.writeFileSync(path.join(dest, "index.html"), html);
  fs.writeFileSync(path.join(dest, "style.css"), css);
  fs.writeFileSync(path.join(dest, "app.js"), js);
  writeSpec(dest, idea);
  return dest;
}

export async function scaffold(idea) {
  if (idea.stack === "html") return scaffoldHtml(idea);
  return scaffoldVite(idea);
}
